### PR TITLE
remove repetitive words

### PR DESCRIPTION
**Pull request by cuishuang**

### CODE REVIEW

**Review by kundan2707 — COMMENTED** [review]
Thanks for identifying so many repeated word in multiple files

**Comment by aramase** [comment]
per https://github.com/kubernetes/apiserver#where-does-it-come-from:

> apiserver is synced from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver. Code changes are made in that location, merged into k8s.io/kubernetes and later synced here.

/close

**Pull request closed without merging**
